using UnityEngine;

namespace WillemMeijer.NMAirTrafficControl
{
    public static class AirTrafficControlData
    {
        public static string[] PlaneSerials = new string[]
        {
            "HV3-84",
            "GQ1-02",
            "VQ6-10",
            "HF-062",
            "GQ6-10",
            "XP-600",
            "KB0-87",
            "YT0-84",
            "LD-128",
            "RR1-28",
            "BF-521",
            "GC5-75",
            "PD-376",
            "OO-332"
        };

        public static string[] ShuttleSerials = new string[] 
        { 
            "DG-780", 
            "DO5-62", 
            "GC-120", 
            "GN-726", 
            "LF-705", 
            "MQ3-17", 
            "JV6-32", 
            "CQ-306", 
            "HK4-82" 
        };

        public static string[] LuggageSerials = new string[] 
        { 
            "SQ2-16", 
            "CQ3-01", 
            "VG5-44", 
            "LF2-01", 
            "CS-612", 
            "FK2-81", 
            "BF-453", 
            "RP3-48", 
            "HO0-46" 
        };

        public static string[] Hangars = new string[] 
        { 
            "Hangar 1", 
            "Hangar 2", 
            "Hangar 3", 
            "Hangar 4", 
            "Hangar 5", 
            "Hangar 6" 
        };

        public static string[] OriginCities = new string[]
        {
            "Ashgabat",
            "Quito",
            "Harare",
            "Ottawa",
            "Bandar Seri Begawan",
            "Wellington",
            "Victoria",
            "Lima",
            "Mogadishu",
            "Riyadh",
            "Dushanbe",
            "Bishkek",
            "Belmopan",
            "Abuja"
        };

        public static int[,] OriginSerialCrossTable = new int[,]
        {
            {0,4,3,3,2,5,4,1,0,5,1,1,1,5},
            {4,1,1,1,5,5,0,5,4,0,5,5,0,0},
            {4,2,1,4,0,0,2,0,5,2,2,4,2,3},
            {4,4,0,0,3,4,4,3,2,5,3,5,0,1},
            {3,3,0,1,5,1,5,2,3,3,3,3,5,3},
            {4,3,2,1,2,0,1,4,0,3,2,3,5,2},
            {2,5,4,4,3,4,3,2,3,4,5,5,1,2},
            {1,5,5,5,3,0,1,5,0,0,3,1,3,4},
            {5,2,4,3,4,1,2,3,2,0,1,5,4,4},
            {5,1,0,3,0,1,1,5,0,3,3,3,4,5},
            {0,3,2,5,2,3,1,3,0,0,0,5,2,4},
            {4,4,4,4,0,3,1,2,2,3,0,0,2,5},
            {5,1,1,0,1,1,3,2,3,2,1,0,0,0},
            {0,2,1,3,4,3,4,0,1,3,3,2,3,5}
        };

        public static string[] AllCities = new string[]
        {
            "Kabul",
            "Tirana",
            "Algiers",
            "Andorra la Vella",
            "Luanda",
            "Saint John's",
            "Buenos Aires",
            "Yerevan",
            "Canberra",
            "Vienna",
            "Baku",
            "Nassau",
            "Manama",
            "Dhaka",
            "Bridgetown",
            "Minsk",
            "Brussels",
            "Belmopan",
            "Porto Novo",
            "Thimphu",
            "Sucre",
            "Sarajevo",
            "Gaborone",
            "Brasilia",
            "Bandar Seri Begawan",
            "Sofia",
            "Ouagadougou",
            "Gitega",
            "Phnom Penh",
            "Yaounde",
            "Ottawa",
            "Praia",
            "Bangui",
            "N'Djamena",
            "Santiago",
            "Beijing",
            "Bogota",
            "Moroni",
            "Kinshasa",
            "Brazzaville",
            "San Jose",
            "Yamoussoukro",
            "Zagreb",
            "Havana",
            "Nicosia",
            "Prague",
            "Copenhagen",
            "Djibouti",
            "Roseau",
            "Santo Domingo",
            "Dili",
            "Quito",
            "Cairo",
            "San Salvador",
            "London",
            "Malabo",
            "Asmara",
            "Tallinn",
            "Mbabana",
            "Addis Ababa",
            "Palikir",
            "Suva",
            "Helsinki",
            "Paris",
            "Libreville",
            "Banjul",
            "Tbilisi",
            "Berlin",
            "Accra",
            "Athens",
            "Saint George's",
            "Guatemala City",
            "Conakry",
            "Bissau",
            "Georgetown",
            "Port au Prince",
            "Tegucigalpa",
            "Budapest",
            "Reykjavik",
            "New Delhi",
            "Jakarta",
            "Tehran",
            "Baghdad",
            "Dublin",
            "Jerusalem",
            "Rome",
            "Kingston",
            "Tokyo",
            "Amman",
            "Nur-Sultan",
            "Nairobi",
            "Tarawa Atoll",
            "Pristina",
            "Kuwait City",
            "Bishkek",
            "Vientiane",
            "Riga",
            "Beirut",
            "Maseru",
            "Monrovia",
            "Tripoli",
            "Vaduz",
            "Vilnius",
            "Luxembourg",
            "Antananarivo",
            "Lilongwe",
            "Kuala Lumpur",
            "Male",
            "Bamako",
            "Valletta",
            "Majuro",
            "Nouakchott",
            "Port Louis",
            "Mexico City",
            "Chisinau",
            "Monaco",
            "Ulaanbaatar",
            "Podgorica",
            "Rabat",
            "Maputo",
            "Nay Pyi Taw",
            "Windhoek",
            "Kathmandu",
            "Amsterdam",
            "Wellington",
            "Managua",
            "Niamey",
            "Abuja",
            "Pyongyang",
            "Skopje",
            "Belfast",
            "Oslo",
            "Muscat",
            "Islamabad",
            "Melekeok",
            "Panama City",
            "Port Moresby",
            "Asuncion",
            "Lima",
            "Manila",
            "Warsaw",
            "Lisbon",
            "Doha",
            "Bucharest",
            "Moscow",
            "Kigali",
            "Basseterre",
            "Castries",
            "Kingstown",
            "Apia",
            "San Marino",
            "Sao Tome",
            "Riyadh",
            "Edinburgh",
            "Dakar",
            "Belgrade",
            "Victoria",
            "Freetown",
            "Singapore",
            "Bratislava",
            "Ljubljana",
            "Honiara",
            "Mogadishu",
            "Pretoria",
            "Bloemfontein",
            "Cape Town",
            "Seoul",
            "Juba",
            "Madrid",
            "Colombo",
            "Khartoum",
            "Paramaribo",
            "Stockholm",
            "Bern",
            "Damascus",
            "Taipei",
            "Dushanbe",
            "Dodoma",
            "Bangkok",
            "Lome",
            "Nuku'alofa",
            "Port of Spain",
            "Tunis",
            "Ankara",
            "Ashgabat",
            "Funafuti",
            "Kampala",
            "Kiev",
            "Abu Dhabi",
            "Washington D.C.",
            "Montevideo",
            "Tashkent",
            "PortVila",
            "Vatican City",
            "Caracas",
            "Hanoi",
            "Cardiff",
            "Sana'a",
            "Lusaka",
            "Harare"
        };
    
        
        public static PlaneData GeneratePlane()
        {
            int s = Random.Range(0, PlaneSerials.Length);
            int o = Random.Range(0, OriginCities.Length);
            int p = Random.Range(100, 300);
            int l = Random.Range(100, 255);

            PlaneData newPlane = new PlaneData(s, o, p, l);

            return newPlane;
        }
    }
}
